micronaut:
  router:
    static-resources:
      default:
        enabled: true
        paths:
          - "classpath:static" # main/resources/static 配下のリソースにアクセスできる
  application:
    name: mnJwtSample
  security:
    enabled: true
    intercept-url-map: # Intercept URL Map で認証の有無を設定できる。主に、画像などの静的リソースを公開するときに使う。
      -
        pattern: "/url-map-anonymous"
        http-method: GET
        access:
          - isAnonymous()
      -
        pattern: "/sample.png" # main/resources/static からの相対パス
        http-method: GET
        access:
          - isAnonymous()
    authentication: bearer
    token:
      jwt:
        enabled: true # default
        generator:
          refresh-token: #signatures.secret と一緒に記述すると、/oauth/access_token へのリフレッシュトークン取得のためののPOSTリクエストがUnauthorizedになる
            enabled: true # default
            jws-algorithm: "HS256" # default
            secret: secret01234567890ABCDEFGHIJKLMNO # 32文字以上
            base64 : false # default
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2